# Generated by Django 6.0 on 2026-01-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
