# Generated by Django 6.0 on 2026-01-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
